spring:
  application:
    name: notification-service

  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: example
      authentication-database: admin
      database: notification-db
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  mail:
    host: smtp.gmail.com
    port: 587
    username: noreply.copilotsons@gmail.com
    password: zitj ggst tglt mqdr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    from: noreply.copilotsons@gmail.com

server:
  port: 8082

debug:
  notification_recipient_email: "mathew.hanybb@gmail.com"

user-service:
  url: http://localhost:8086

# logging configuration to create the file and unify log format
logging:
  file:
    name: logs/app.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
