#spring:
#  application:
#    name: api-gateway
#  main:
#    web-application-type: reactive
#  cloud:
#    spring:
#      cloud:
#        gateway:
#          routes:
#            - id: user-service
#              uri: http://localhost:8080
#              predicates:
#                - Path=/user/**
#                - Path=/auth/**
#
#            - id: product-service
#              uri: http://localhost:8082
#              predicates:
#                - Path=/products/**
#
#server:
#  port: 8086
#
