spring:
  cloud:
    gateway:
      routes:
        - id: group-chat-service
          uri: lb://GROUP-CHAT-SERVICE
          predicates:
            - Path=/group-chat/**
          filters:
            - AuthenticationFilter


        - id: chat-service
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/chat/**
          filters:
            - AuthenticationFilter

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/auth/**

  application:
    name: Gateway-Service

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/