server:
  port: 8765
spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      inetutils:
        default-hostname: localhost
        default-ip-address: 127.0.0.1
      routes:
        - id: user-service
          uri: http://localhost:8086
          predicates:
            - Path=/auth/**,/user/**,/manageUser/**
          filters:
            - StripPrefix=0

        - id: chat-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/messages/**,/chats/**
          filters:
            - StripPrefix=0

        - id: notification-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/notification-settings/**,/debug/**,/api/seed/notifications/**,/notifications/**
          filters:
            - StripPrefix=0
        - id: groupChatService
          uri: http://localhost:8083
          predicates:
            - Path=/groupChat/**,/groupMessage/**
          filters:
            - StripPrefix=0
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s

  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  blacklist:
    expiration-time: 300
userService:
  url: http://localhost:8086


