apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: farahalfawzy/user-service:latest  # Replace with the actual image for your app
          ports:
            - containerPort: 8086  # Exposed port inside the container
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/your_postgres_db
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: SPRING_CACHE_TYPE
              value: "redis"
            - name: SPRING_DATA_REDIS_HOST
              value: "redis"
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
            - name: NOTIFICATION_SERVICE_URL
              value: "http://notification-service:8082"
            - name: JWT_BLACKLIST_EXPIRATION_TIME
              value: "600"
            - name: JWT_ACCESS_TOKEN_VALIDITY
              value: "600000"
            - name: JWT_REFRESH_TOKEN_VALIDITY
              value: "518400000"





