apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: cm9vdA==
  MONGO_INITDB_ROOT_PASSWORD: ZXhhbXBsZQ==
  Notification_service_URI: bW9uZ29kYjovL3Jvb3Q6ZXhhbXBsZUBtb25nby0wLm1vbmdvOjI3MDE3L25vdGlmaWNhdGlvbl9kYj9hdXRoU291cmNlPWFkbWlu
  Groupchat_service_URI: bW9uZ29kYjovL3Jvb3Q6ZXhhbXBsZUBtb25nby0wLm1vbmdvOjI3MDE3L2dyb3VwX2NoYXRfZGI/YXV0aFNvdXJjZT1hZG1pbg==
  Chat_service_URI: bW9uZ29kYjovL3Jvb3Q6ZXhhbXBsZUBtb25nby0wLm1vbmdvOjI3MDE3L2NoYXRfZGI/YXV0aFNvdXJjZT1hZG1pbg==