services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false

    depends_on:
      - mongo

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: your_postgres_db
      POSTGRES_USER: your_pg_username
      POSTGRES_PASSWORD: your_pg_password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis_cache:
    image: redis:latest
    container_name: redisCache
    ports:
      - "6379:6379"

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisInsight
    ports:
      - "5540:5540"
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
    ports:
      - "80:80"
    depends_on:
      - postgres

  chats-service:
    build: ../chat-service
    container_name: chats-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=e2e
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - SPRING_DATA_MONGODB_URI=mongodb://root:example@mongo:27017/chats-db?authSource=admin
      - USER_SERVICE_URL=http://user-service:8086

  group-chat-service:
    build: ../groupChatService
    container_name: group-chat-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=e2e
      - SPRING_DATA_MONGODB_URI=mongodb://root:example@mongo:27017/group-chat-db?authSource=admin
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - USER_SERVICE_URL=http://user-service:8086

  notification-service:
    build: ../notification-service
    container_name: notification-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=e2e
      - SPRING_DATA_MONGODB_URI=mongodb://root:example@mongo:27017/notification-db?authSource=admin
      - SPRING_DATA_MONGODB_USERNAME=root
      - SPRING_DATA_MONGODB_PASSWORD=example
      - SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE=admin
      - SPRING_DATA_MONGODB_DATABASE=notification_db
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - USER_SERVICE_URL=http://user-service:8086
      - SPRING_MAIL_HOST=mailhog
      - SPRING_MAIL_PORT=1025

  user-service:
    build: ../userService
    container_name: user-service
    ports:
      - "8086:8086"
    environment:
      - SPRING_PROFILES_ACTIVE=e2e
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/your_postgres_db
      - SPRING_DATASOURCE_USERNAME=your_pg_username
      - SPRING_DATASOURCE_PASSWORD=your_pg_password
      - SPRING_REDIS_HOST=redisCache
      - NOTIFICATION_SERVICE_URL=http://notification-service:8082

volumes:
  mongodb_data:
  postgres-data:
