apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: eW91cl9wZ191c2VybmFtZQ==
  POSTGRES_PASSWORD: eW91cl9wZ19wYXNzd29yZA==
  POSTGRES_DB: eW91cl9wb3N0Z3Jlc19kYg==
