apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-deployment
  namespace: chat-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apigateway-service
  template:
    metadata:
      labels:
        app: apigateway-service
    spec:
      containers:
      - name: apigateway
        image: nairuzy/apigateway:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: SPRING_CLOUD_KUBERNETES_DISCOVERY_NAMESPACE
          value: "chat-app"
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi" 