apiVersion: v1
kind: Service
metadata:
  name: apigateway-service
  namespace: chat-app
  labels:
    app: apigateway-service
spec:
  type: NodePort
  selector:
    app: apigateway-service
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
      name: http