name: Build and Push Docker Images

on:
  workflow_run:
    workflows: ["End-to-End Tests"]
    types:
      - completed
  workflow_dispatch:

env:
  REGISTRY_USERNAME: copilotandsons
  REGISTRY_PASSWORD: dckr_pat_IQTvVI_STef4y2fNf_-5cImmy-E # Really bad idea, but since I don't have access to the settings, let's just hard code it.
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 23
      uses: actions/setup-java@v3
      with:
        java-version: '23'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: |
        mvn clean install -DskipTests
        mvn package -DskipTests

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        username: ${{ env.REGISTRY_USERNAME }}
        password: ${{ env.REGISTRY_PASSWORD }}

    - name: Build and push chat-service
      run: |
        docker build -t ${{ env.REGISTRY_USERNAME }}/chat-service:latest ./chat-service
        docker push ${{ env.REGISTRY_USERNAME }}/chat-service:latest

    - name: Build and push gateway
      run: |
        docker build -t ${{ env.REGISTRY_USERNAME }}/api-gateway-service:latest ./gateway
        docker push ${{ env.REGISTRY_USERNAME }}/api-gateway-service:latest

    - name: Build and push group-chat-service
      run: |
        docker build -t ${{ env.REGISTRY_USERNAME }}/group-chat-service:latest ./groupChatService
        docker push ${{ env.REGISTRY_USERNAME }}/group-chat-service:latest

    - name: Build and push notification-service
      run: |
        docker build -t ${{ env.REGISTRY_USERNAME }}/notification-service:latest ./notification-service
        docker push ${{ env.REGISTRY_USERNAME }}/notification-service:latest

    - name: Build and push user-service
      run: |
        docker build -t ${{ env.REGISTRY_USERNAME }}/user-service:latest ./userService
        docker push ${{ env.REGISTRY_USERNAME }}/user-service:latest 
